### ISSUE TITLE
Search Listings code doesn't seem to work

### ISSUE THREAD

**Issue by obinopaul** [johnbalvin/pyairbnb#8]
Hi John, 

I appreciate you developing this repo, its amazing. I however noticed that the code to search listings doesn't seem to work, and one or two others.

Here is the example code you gave in the ReadMe.

```
import pyairbnb
import json

# Define search parameters
currency = "MXN"  # Currency for the search
check_in = "2025-02-01"  # Check-in date
check_out = "2025-02-04"  # Check-out date
ne_lat = -1.03866277790021  # North-East latitude
ne_long = -77.53091734683608  # North-East longitude
sw_lat = -1.1225978433925647  # South-West latitude
sw_long = -77.59713412765507  # South-West longitude
zoom_value = 2  # Zoom level for the map

# Search listings within specified coordinates and date range
search_results = pyairbnb.search_all(check_in, check_out, ne_lat, ne_long, sw_lat, sw_long, zoom_value, currency, "")

# Save the search results as a JSON file
with open('search_results.json', 'w', encoding='utf-8') as f:
    f.write(json.dumps(search_results))  # Convert results to JSON and write to file
```

it doesnt seem to produce any results

**Comment by johnbalvin** [comment]
it should be fixed now

**Comment by obinopaul** [comment]
Hi, i just checked it again and it still doesn't work.

Please try to run any of these codes.

`import pyairbnb
import json

# Define search parameters
currency = "MXN"  # Currency for the search
check_in = "2025-02-01"  # Check-in date
check_out = "2025-02-04"  # Check-out date
ne_lat = -1.03866277790021  # North-East latitude
ne_long = -77.53091734683608  # North-East longitude
sw_lat = -1.1225978433925647  # South-West latitude
sw_long = -77.59713412765507  # South-West longitude
zoom_value = 2  # Zoom level for the map

# Search listings within specified coordinates and date range
search_results = pyairbnb.search_all(check_in, check_out, ne_lat, ne_long, sw_lat, sw_long, zoom_value, currency, "")

print(search_results)
`
or this
`import pyairbnb
import json
room_url=r"https://www.airbnb.com/rooms/30931885"
data = pyairbnb.get_reviews(room_url,"")
print(data)`

this too

`import pyairbnb
import json
host_id = 0
api_key = pyairbnb.get_api_key("")
listings = pyairbnb.get_listings_from_user(host_id,api_key,"")
print(listings)`

**Comment by johnbalvin** [comment]
Did you upgrade the package? 
`pip install pyairbnb --upgrade`
